### ISSUE TITLE
[enhancement] using delete key in "MoreClipboard Contents" view

### ISSUE THREAD

**Issue by anb0s** [mikhail-barg/moreclipboard#2]
Thanks for the very useful plugin :)

In "MoreClipboard Contents" view i want to delete the selected line with delete key. in Eclipse we have  views where it works, like Problems view etc. and would be nice to have here too.

**Comment by mikhail-barg** [comment]
Thanks for feedback! Sure, should be no problem. I just need to check how to register that binding properly.

**Comment by mikhail-barg** [comment]
Finally managed to make it properly. Now it's possible to configure key bindings for all 4 actions in MC Contents view. And "Remove Current" is bound to "Delete" by default.

Took me 3 days instead of 15 minutes (.The problem was that that I wanted to implement it via Commands/Handlers feature, instead of outdated Actions. But E4 has a lot of regressions in that place. So I ended up in some combined chimera.

**Comment by anb0s** [comment]
cool :)

yes, the command-handling in Eclipse for E4 feels not consistent, i've also searched a lot for solutions...

**Comment by anb0s** [comment]
verified with v1.4.1 --> works like expected :+1:
